<Project>
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <LangVersion>preview</LangVersion>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <BlazorWebAssemblyOmitDebugProxyOutput Condition="'$(Configuration)' == 'Release'">true</BlazorWebAssemblyOmitDebugProxyOutput>
  </PropertyGroup>
</Project>
