<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.Server" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Piston.Engine\Piston.Engine.csproj" />
    <ProjectReference Include="..\Piston.Mcp\Piston.Mcp.csproj" />
    <ProjectReference Include="..\Piston.Protocol\Piston.Protocol.csproj" />
  </ItemGroup>
</Project>
